#!/usr/bin/env bash
set -euo pipefail

# Simple build script that supports Release (default) and Debug builds.
# Usage: ./build.sh [debug]
#        ./build.sh --debug
#        ./build.sh -d

BUILD_TYPE=Release

if [ $# -gt 0 ]; then
  case "$1" in
    debug|-d|--debug)
      BUILD_TYPE=Debug
      ;;
  esac
fi

echo "Building with CMake build type: ${BUILD_TYPE}"

[ -d build ] && rm -r build

# Install Conan dependencies for the selected build type
conan install . --build=missing -s build_type=${BUILD_TYPE}

# Configure CMake with the toolchain generated by Conan for the selected build type
cmake -S . -B build \
  -DCMAKE_TOOLCHAIN_FILE=build/${BUILD_TYPE}/generators/conan_toolchain.cmake \
  -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

# Build
cmake --build build

